name: HTML Build

on:
  push:
    paths:
        - '*.ipynb'   

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
    - name: Convert notebook to basic html
      run: jupyter nbconvert playing-word-embeddings.ipynb --to html --template basic
    - name: Commit the output html
      run: |
        git config --global user.email "guillem.orellana@gmail.com"
        git config --global user.name "Guillem96"
        git add playing-word-embeddings.ipynb
        git commit -m "Auto commit: HTML build"
        git push origin master
